# Server Port config
server.port=8081

# Logging config
logging.level.root=INFO
logging.level.com.baeldung=INFO

# REST config
smkex.public-zone=/public/*
smkex.private-zone=/private/*

# Websocket config
smkex.public-ws-zone=/public/smkex-websocket/*
smkex.private-ws-zone=/private/smkex-websocket/*

# Auth config
smkex.auth-username=root
smkex.auth-password=smkex

# Messages config
smkex.message-expire-time-ms=180000
