
applicationName = Smkex

android.enableJetifier=true

android.useAndroidX=true

android.useDeprecatedNdk=true

android.enableBuildCache=true

org.gradle.caching=true

org.gradle.daemon=true

org.gradle.parallel=true

org.gradle.jvmargs=-Xmx2046m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

