#ifndef MP_NETWORK_STATE_H_
#define MP_NETWORK_STATE_H_

typedef enum {
	MP_NETWORK_UNREACHABLE,
	MP_NETWORK_WIFI,
	MP_NETWORK_GPRS,
	MP_NETWORK_EDGE,
	MP_NETWORK_WCDMA,
	MP_NETWORK_LTE,
	MP_NETWORK_OTHER
} mp_network_state_t;

#endif /* MP_NETWORK_STATE_H_ */
